### ISSUE TITLE
Force lowercase usernames

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#100]
Lets just make all usernames lowercase as it makes things tidier

**Comment by helveticade** [comment]
We can do this pretty easily with CSS?

**Comment by daviddahl** [comment]
We dont want mixed case in the database

**Comment by Bennyoak** [comment]
It may be easier to allow camelCase in the field and just lower it in the background. If there isn't anything to tell the user lowercase is policy, there may be some confusion the next time they log in and their username doesn't appear as expected.

**Comment by daviddahl** [comment]
@helveticade text-transform: lowercase does not actually change the text in the DOM.

**Comment by daviddahl** [comment]
Fixed on client in https://github.com/Crypton/statusapp/commit/b5c513e2b8f51e260e9d72fa57fadd1fdbe9699a
