### ISSUE TITLE
Move remember password to Options

### ISSUE THREAD

**Issue by Bennyoak** [Crypton/statusapp#101]
Since the password is stored by default anyway. This option should be moved to the options page. I noticed unchecking it from the beginning causes all sorts of strange little issues. From the options page, make the Forget Passphrase button a toggle between "Forget" and "Remember"

**Comment by daviddahl** [comment]
+1

**Comment by daviddahl** [comment]
I'm thinking for now we just remember the password and not offer an option as we already have a "Forget Credentials" action
