### ISSUE TITLE
Latest UI updates trash iPhone5

### ISSUE THREAD

**Issue by Bennyoak** [Crypton/statusapp#115]
Setting button doesn't click, either.

![img_3238](https://cloud.githubusercontent.com/assets/2933700/9640360/d951206a-5176-11e5-808d-d750487fc5a0.jpg)
![img_3239](https://cloud.githubusercontent.com/assets/2933700/9640359/d9500cfc-5176-11e5-8e00-0b695f18e531.jpg)

**Comment by daviddahl** [comment]
yes! This branch is currently fugly. A  WIP. We will try to patch it this afternoon.

**Comment by daviddahl** [comment]
it is fugly on all devices

**Comment by Bennyoak** [comment]
I do like where it's going, tho.

**Comment by helveticade** [comment]
💩

**Comment by helveticade** [comment]
We fixed this in b-3!
