### ISSUE TITLE
Redesign of signup/signin screen

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#119]
So I'm looking at the sign up screen and wanted to clarify - is there a specific purpose behind the Switch User button when signed out?
![simulator screen shot 7 sep 2015 4 52 24 am](https://cloud.githubusercontent.com/assets/737950/9706099/e84a166c-551d-11e5-977d-bb44a27c5965.png)

**Comment by daviddahl** [comment]
No, I just wanted to address the use case of multiple accounts which we can actually do better now with the keychain functionality we have

**Comment by daviddahl** [comment]
In short we can leave it out for now until we design that ux specifically

**Comment by daviddahl** [comment]
Fixed in b-4, will yet need some design love
