### ISSUE TITLE
iOS: iPhone 5 iOS 8: feed does not load

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#12]
Testing with Chris, his iPhone could update my feed but his feed was blank

**Comment by cHRIScDammit** [comment]
It's the original 5, with iOS 8.3 on it, if that matters.

**Comment by daviddahl** [comment]
I wonder what @devgeeks would think about this? :)

**Comment by daviddahl** [comment]
This might be related to #19

**Comment by daviddahl** [comment]
Have not seen this lately, marking as invalid
