### ISSUE TITLE
TouchID Not Displaying On Manual Login

### ISSUE THREAD

**Issue by Bennyoak** [Crypton/statusapp#123]
One little bug...
Steps to reproduce:

Create or login to account manually (e.g. forget credentials or delete and reinstall app)
Login then go to Options
TouchID option will NOT visible
Close app then log back in with credentials saved
TouchID option visible
I suspect since it's not finding anything in the keychain it's hiding it.

**Comment by daviddahl** [comment]
Yeah, this is still an issue...
