### ISSUE TITLE
Support Mentions

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#124]
For now, we just need to style mentions with a subtle background-color change to the post. @helveticade can tell us what color to use:)

**Comment by daviddahl** [comment]
Also, we talked about using ~ instead of @ - what say you all?

**Comment by bytex64** [comment]
I'm gonna say yes, purely because I'm a hardcore UNIX geek. (I can also accept that this is a good reason not to do it.)

**Comment by daviddahl** [comment]
:)

**Comment by daviddahl** [comment]
@helveticade what color should we use for mentions?

**Comment by daviddahl** [comment]
fixed in b-4, 601de90d8f3783abefcb5c2f0a04b9e529c12c8c
