### ISSUE TITLE
BB10 running Android build UI is pushed up

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#13]
See screengrab
![bb-10-chip-screenshot](https://cloud.githubusercontent.com/assets/23880/7211165/e22bc5de-e51d-11e4-9714-5b4d851e31d9.png)

**Comment by daviddahl** [comment]
Not sure if the plugins in use will even work on the BB android runner??

**Comment by bytex64** [comment]
It should work when run as an Android app. BB10's Android environment is fairly complete in 10.3.1 (it runs Firefox, for example). It might not work if you built it as a BB10 Webworks app.

**Comment by helveticade** [comment]
Dropping BB10 support.
