### ISSUE TITLE
Login issues iphone 5S 9.0

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#133]
___
Have attempted to log in using two past accounts that were previously usable 
--> currently not able to connect. 
___
Have attempted to create three new accounts 
--> Kloak hangs at creation and verification. 
--> Longest period I have left process to attempt to complete was ~3 hours. 
--> Must force close and reload to get out of the "creation and verification" page. 
--> I have attempted creation / login the past three days (I think)
___

**Comment by daviddahl** [comment]
Maybe you should restart the device? Also, does your device have a fingerprint reader?

**Comment by daviddahl** [comment]
I don't have a 5S to test on unfortunately

**Comment by devgeeks** [comment]
Yes, 5S has fingerprint / touchID

**Comment by daviddahl** [comment]
Also, you should completely uninstall it and then re-install it from Apple's Test Flight

**Comment by daviddahl** [comment]
Ok, so I am pretty sure I know what happened here. I think you tried to create the same account again - or you may have used characters in your account name that are not allowed. The error was just dropping off silently and not notifying the user. see the fix I added today: https://github.com/Crypton/statusapp/commit/ea80e398d41dba892bd8c31cfff39a5097cdf75c#diff-de84680786400b531e559419da4a7248R195

**Comment by xpkoala** [comment]
Problem seems to be fixed. Just for clarification's sake I did not re-install Kloak through TestFlight.  I'll attempt to make more accounts that could cause issues and report the findings later tonight (using -,$!>).  I had a list of accounts I was testing for stuff like this and I seem to have misplaced it at the moment. Cheers!
