### ISSUE TITLE
Error message not readable on account already exists - iphone 5s 9.0.1

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#144]
Upon attempting to create an account that already exists the screen will flash and show a red error box for a split second before taking the user back to the create account page.

>Create an account using a username that exists.
>A page will flash the screen, can only make out red error box on lower portion of screen.
>Taken to create account screen.

I'm not sure if the iphone is skipping over an error page saying that the account is not available or if it is a screen the user is not supposed to see. I'm not able to take a picture of the screen flash.

**Comment by daviddahl** [comment]
this is fixed in the b-5 branch, going to be released i hope on wednesday

**Comment by daviddahl** [comment]
fixed here https://github.com/Crypton/statusapp/commit/d29281dce8bfc12c3ab4ddd55d95144f0fa8c7ad
