### ISSUE TITLE
Errors generated upon picture manipulation for contact card

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#156]
Errors generated when manipulating a photo for use with the contact card.
iphone 5s 9.0.1

Example 1a: Canceling the selection of 'taking a new picture' to update contact card.
>-Select picture button on your Kloak contact card.
>-Select 'Snap Card Photo'
>-Cancel photo
>-See first for errors

Example 1b: Canceling the selection of 'Choose Card Image' to update contact card.
>-Select picture button on your Kloak contact card.
>-Select 'Choose Card Image'
>-Cancel
>-See second photo for errors

![1a](https://cloud.githubusercontent.com/assets/11012743/10386059/b7a00e50-6e17-11e5-992d-7d1a2507349a.PNG)
---
![1b](https://cloud.githubusercontent.com/assets/11012743/10386061/b8fc150a-6e17-11e5-99b8-06520d29c380.PNG)

**Comment by xpkoala** [comment]
The exact same errors occur when selecting the same options on loading a picture to your timeline.

**Comment by daviddahl** [comment]
GAh!

**Comment by daviddahl** [comment]
fixed in 750195602e237e51eeb707007ea45b7cc8afea27
