### ISSUE TITLE
Contact card picture replaced with picture from friends contact card

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#157]
Avatar picture replaced with avatar picture of user on friend list.
iphone 5s 9.0.1

>-Can not currently replicate.

The photo below was not modified in any way. Upon visiting the edit contact card page the following picture is what was presented. Prior to this I did not select Cade's puppy as a picture and had not stored the photo anywhere on my phone.

![cade photo](https://cloud.githubusercontent.com/assets/11012743/10386208/a7b76928-6e19-11e5-8a81-009c58b2d95f.PNG)

**Comment by xpkoala** [comment]
I think I got this reproducible, testing now...

**Comment by xpkoala** [comment]
Upon some further investigation it looks as if the picture field (once removed via the save photo bug) is an open slot. You can cycle through different friend's contact cards and have their picture replace the field. Most likely more superficial than originally thought. Solving the 'saving photo' bug --> https://github.com/Crypton/statusapp/issues/156 would most likely fix this issue as well.

**Comment by daviddahl** [comment]
Ok, I think this is because of holding a reference to any avatar inside the contactCard object and then we don't set it back to null before another picture / avatar operation

**Comment by daviddahl** [comment]
Fixed in e625f40c8012000eac72f240593290200939d31c
