### ISSUE TITLE
iphone keyboard overlays blocks text fields

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#158]
On certain screens the iphone keyboard overlay blocks the ability to view current fields. Have found a few.
iphone 5s 9.0.1

>-Select fields to enter text

The following two pictures are from the start screen. The first picture is before selecting the text field. The second picture is with my new username typed in. You are not able to move either the screen or keyboard or background application to view your entry, you must cancel the keyboard.

![start screen](https://cloud.githubusercontent.com/assets/11012743/10386287/e6d521c6-6e1a-11e5-9aa8-f81edfab8741.png)

![username entered](https://cloud.githubusercontent.com/assets/11012743/10386288/eabb62dc-6e1a-11e5-9493-825cff43e920.png)

___
___

The same issue occurs on the change password screen. See image below.

![change pass](https://cloud.githubusercontent.com/assets/11012743/10386302/362458f0-6e1b-11e5-9302-4fac0ba4a44d.png)

**Comment by daviddahl** [comment]
I think the thing to do is to shrink the logo way down on this screen, or remove it completely

**Comment by daviddahl** [comment]
On the passphrase screen there is too much padding and I think 3 rows in the textarea, we should use 2

**Comment by daviddahl** [comment]
fixed in 8c7c4e08f84a1771ef54f8f33217a3f30d545b85
