### ISSUE TITLE
Backdrop image interferes with text

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#159]
The white image in the background of the password generator page interferes with the ability to see current text.

iphone 5s 9.0.1

>-Create new account
>-Get to password creation screen

Two images below show examples. Suggest making the background a harder color or less transparent while on screen.

![password1](https://cloud.githubusercontent.com/assets/11012743/10386341/a8ac42de-6e1b-11e5-9fe1-1f5ccebdecb1.png)

![password2](https://cloud.githubusercontent.com/assets/11012743/10386342/ab61696e-6e1b-11e5-9426-d86f5901b2d2.png)

**Comment by daviddahl** [comment]
D'oh! Great report. We will have to fix this in emulator. Sorry!

**Comment by daviddahl** [comment]
Fixed in 8c7c4e08f84a1771ef54f8f33217a3f30d545b85
