### ISSUE TITLE
Selecting 'Cancel' on first bio prompt does not cancel

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#160]
After creating an account and getting past the build phase user is prompted with a menu to generate a 'Biography'. If you select 'Cancel' the menu will save whatever information is currently in the text field and apply it to your contact card under biography.

iphone 5s 9.0.1

>-Create new account
>-Select 'Cancel' at Enter Biography menu

Screen grabs below.

![image4](https://cloud.githubusercontent.com/assets/11012743/10386443/fd3fc630-6e1c-11e5-94c9-353b3d0ca5c5.png)

![image3](https://cloud.githubusercontent.com/assets/11012743/10386445/ff6a6d48-6e1c-11e5-81cc-5b861801859f.png)

**Comment by daviddahl** [comment]
weird, I am not be handling the cancel callback. Thought I was.

**Comment by daviddahl** [comment]
Fixed in 9d02e6ed967e7d8b8700c5a7055ab861adada10c
