### ISSUE TITLE
Failure to change password if you have already selected 'Forget Credentials'

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#161]
After selecting 'Forget credentials' in the options page the user is not able to change the passphrase even after supplying the correct passphrase. I feel like this is correct but maybe provide a better error message or notify the passphrase can not be changed if it is forgotten?

iphone 5s 9.0.1

>-Select 'Forget credentials'
>-Select 'Change passphrase'
>-Supply passphrase for the account and new passphrase
>-Error

See below pictures; the passphrase for that account is abc (such secure; very crypto)

![img_1051](https://cloud.githubusercontent.com/assets/11012743/10386537/24f775be-6e1e-11e5-9c0e-efb1952f29aa.PNG)

![img_1052](https://cloud.githubusercontent.com/assets/11012743/10386538/270b249a-6e1e-11e5-85fa-f5c8d7ba9dc4.PNG)

**Comment by daviddahl** [comment]
Ah yes, GREAT CATCH. I know why this is doing it. I probably need to make password change not possible once you "forget credentials". So many side effects!

**Comment by daviddahl** [comment]
Looks like we throw in keyChain.removePassphrase() - we assume the credentials exists.

**Comment by daviddahl** [comment]
fixed in a7ce097a62041064467681620a5ab3884da48842
