### ISSUE TITLE
Can't scan anyone's QR

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#162]
It fails with no error message. Others report that scanning MY QR fails with 'account not found'

**Comment by daviddahl** [comment]
I think you should start over and create a new account. Something has made your account go kerplunk. Very weird!

**Comment by daviddahl** [comment]
I would be very interested in if your account was ever really created on the server. @dhain could tell us that.

**Comment by reneelynn** [comment]
Still having the same problem with new account "workdammit". Happy to send an email with my contact card to confirm whether you still get "Account Not Found" when trying to scan mine.

**Comment by daviddahl** [comment]
yes please. Just please confirm the build here (in the about screen)

**Comment by reneelynn** [comment]
0.5.0pre 20151007

**Comment by daviddahl** [comment]
That is an old build

**Comment by daviddahl** [comment]
0.5.2 is current

**Comment by daviddahl** [comment]
Just figured it out. Your buil dis using the staging server! Everyone else is using the production server!

**Comment by reneelynn** [comment]
Where is 0.5.2 downloadable from? https://zk.gs/ZK/ shows 0.5.1 (0.0.3)
