### ISSUE TITLE
Posts containing removed text & many new lines fails and breaks Kloak

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#165]
I'm not sure the amount of new lines needed to break the post feature. After X amount of new lines and removed input are attempted to be submitted the post fails and returns you to the Timeline with the post box intact. Soft closing the application does not remove the text field. User is also unable to navigate to configure or contact tabs.

iphone 5s 9.0.1

>-Have some random information copied to clipboard
>-Select make post button
>-Paste clipboard
>-Use 'select all' command on phone.
>-Delete text via backspace
>-Hit return ~20+ times
>-Select 'post'
>-Post fails and returns user to Timeline with text box still open.

![img_1058](https://cloud.githubusercontent.com/assets/11012743/10411915/d74e568e-6f3a-11e5-85c4-a0e72e23d18b.PNG)

![img_1059](https://cloud.githubusercontent.com/assets/11012743/10411916/db82a75a-6f3a-11e5-8065-5ec29654c291.PNG)

**Comment by daviddahl** [comment]
Fixing this via max-height 5rem :)

**Comment by daviddahl** [comment]
Fixed in 5a216559056c4b74c556f6bec95839e58cd5b9ca
