### ISSUE TITLE
Selecting text from Timeline sometimes breaks

### ISSUE THREAD

**Issue by xpkoala** [Crypton/statusapp#167]
I should state that I have not been able to reliably reproduce this issue. Upon manipulation, the text grab fields can sometimes break or select more information than was chosen. My only theory at the moment is there are issues with boundaries and text boxes as they are presented on the Timeline. I was not able to screen-grab as many as I had hoped.

iphone 5s 9.0.1

Through testing I have been able to do the following (again not reproducible):

*By slowly selecting text on two lines I have 'grabbed' all text on screen.
*Moving the 'grabbers' around photos can cause abnormally large or small selections.
*'Grabbing' smaller text (date/time) can cause no selection or abnormally large selections.
*Manipulating the 'grabbers' can cause them to break the 'rectangle' pattern they should follow 

>-Navigate to Timeline
>-Hold finger above any text to generate the 'text grab quotes'.
>-Move the 'grabbers' around to select different amounts of text.

![img_1056](https://cloud.githubusercontent.com/assets/11012743/10412092/af4d82bc-6f40-11e5-9103-ee1759534d70.PNG)
![img_1057](https://cloud.githubusercontent.com/assets/11012743/10412093/b38a715a-6f40-11e5-828b-a6a359557a1d.PNG)

**Comment by daviddahl** [comment]
WONTFIX (read CANTFIX)
