### ISSUE TITLE
Make sure build supports iOS 8.x

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#174]
I keep looking at the xCode build settings and am confused about what OS versions you support when you select the version. I think it was due to a build not working in an iOS 9 emulator?

**Comment by daviddahl** [comment]
maybe @devgeeks knows?

**Comment by devgeeks** [comment]
There shouldn't be any reason to NOT support iOS 8.1+

**Comment by daviddahl** [comment]
so, my build would fail when I set it to 8.4 or whatever in xCode

**Comment by daviddahl** [comment]
i should ask, how do you properly do this?

**Comment by devgeeks** [comment]
Hrm, it might be something to do with plugins you have that I don't, but it *should* work. It worked before 9 came out, didn't it?

**Comment by daviddahl** [comment]
Building this tonight with support back to 8.1...
