### ISSUE TITLE
iOS9: Display Passphrase clipping 

### ISSUE THREAD

**Issue by daevski** [Crypton/statusapp#175]
Currently, long passphrases are clipped when displayed.

Steps to reproduce:
Preconditions: Ensure your passcode is long.. Mine is 32 char, but more than 
1) Click on the settings gear icon in the top left.
2) Click on Display Passphrase

Screenshot:
![kloak-display-passphrase-clipping](https://cloud.githubusercontent.com/assets/1388502/10517097/44481fb2-7329-11e5-84e8-d35fb0550269.jpg)

**Comment by daviddahl** [comment]
Gah! I should have tested that better. Thanks for the report!

**Comment by daviddahl** [comment]
We should probably use a "sticky" UI widget here anyway. This was a shortcut just to get something working.

**Comment by daevski** [comment]
Yes, should also be sticky. It will disappear pretty quickly! (I won't write that defect up for you. lol)

**Comment by daviddahl** [comment]
About to commit this change. @helveticade will no doubt want to tweak it
![password-display](https://cloud.githubusercontent.com/assets/23880/10520934/9b11148a-7332-11e5-8d88-26f4da6d4f34.png)

**Comment by daevski** [comment]
(thumbs up emoji)
