### ISSUE TITLE
iOS9: Missing ability to remove location for current post

### ISSUE THREAD

**Issue by daevski** [Crypton/statusapp#176]
(This is more of an enhancement request, but did not know where to place it.)

When making a new post, the user should have the option to remove location information for that post if their configured to share location data with the Kloak App on iOS.

Steps to reproduce:
Preconditions: Ensure that you are sharing location data with Kloak App
1) Create a new post add a photo to the post.
2) Notice that the interface has no option to remove location data, and the location data is included under your picture preview. Also note that the"add location" option still exists even thought the info is already included.

Screenshots:
![kloak-missing-remove-location-data-option-1](https://cloud.githubusercontent.com/assets/1388502/10517381/7cb9d600-732a-11e5-858f-581fe3f946da.jpg)
![kloak-missing-remove-location-data-option-2](https://cloud.githubusercontent.com/assets/1388502/10517382/7cbc5452-732a-11e5-8377-a617d6c730f5.jpg)

**Comment by daviddahl** [comment]
fixed in f0ffd5b6943db25276e4d6b76854411015ceee22
