### ISSUE TITLE
Does not scale for iPad

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#179]
![img_0314](https://cloud.githubusercontent.com/assets/3867179/10544438/0598ff96-73e9-11e5-94d9-c7babc24744e.PNG)

**Comment by daviddahl** [comment]
Yeah, I was under the impression xCode could prevent iPads from installing. We just do not have bandwidth to build a bigger UI yet. I hope soon.

**Comment by daviddahl** [comment]
@devgeeks Is there a way to do this automatically - as in scale it up?

**Comment by reneelynn** [comment]
I'm personally glad I can install in iPad; it's much more efficient for me to have 2 devices running simultaneously for testing purposes.

**Comment by shibco** [comment]
Tap the 2x button in your bottom right hand corner and it will behave like any other non-universal iOS app. Proper iPad support may come over time.
