### ISSUE TITLE
Auto generated pass phrase does not seem to allow re-login

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#182]
I have 2 accounts I manually chose passwords for and 3 accounts that have auto generated pass phrases.

The 2 accounts with manually selected passwords can log out (with the help of "Forget Credentials"/ force quit) and back in at whim. The 3 accounts with auto generated pass phrases throw "incorrect credentials" errors when I try to log back in. I suppose it is possible that I have some typo in the pass phrase, but I have recreated with 3 separate accounts and multiple attempts at inputting the pass phrase now. 

The latest attempt was done on a secondary device while I used the "display passphrase" option on the first device that was still logged in, so this is also not a matter of writing down credentials incorrectly. 

iOS6 
Kloak build: 0.6.0pre 20151013

**Comment by reneelynn** [comment]
I just changed the password on the last of these 3 auto-gen pass accounts to one of my own devising and was able to log in on my secondary device.

**Comment by daviddahl** [comment]
ok, looking into it

**Comment by daviddahl** [comment]
There are 12400 words in the passphrase corpus and all of them are ASCII - I just checked. We also trim() the passphrase before using it. I wonder if you are typing a return character into it, but that is also trimmed. very strange.

**Comment by daviddahl** [comment]
Figured it out! input element was cutting off the passphrase at 32 chars!

**Comment by reneelynn** [comment]
verified fixed in 0.7.0 20151017 build
