### ISSUE TITLE
corner case: Touch ID remains for multiple users

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#186]
1) Enable touchID for a user
2) Force quit app and reopen
3) Create a new user
4) force quit app and reopen

TouchID will still be in effect for the new user. 

iOS6 
Kloak build: 0.6.0pre 20151013

**Comment by daviddahl** [comment]
Thanks!

**Comment by daviddahl** [comment]
Wait, was TouchId in effect for the original user after creating a new user?

**Comment by reneelynn** [comment]
once you create a new user it doesn't save the credentials for the first user, so no?

**Comment by daviddahl** [comment]
I think this is fixed in the new build

**Comment by reneelynn** [comment]
Build 0.7.0 20151017 fixed

**Comment by daviddahl** [comment]
I think after re-reading the issue STR, this is not a bug. There might be some new functionality wanted, like remembering all of the handles a user uses to login - and allowing touchID for all of them, but the behavior here is expected, as we only remember the last user( to login) credentials.

**Comment by reneelynn** [comment]
so you don't consider it a bug that user 2, who never personally set the preference for touchid, automatically has touchid enabled?

**Comment by daviddahl** [comment]
Yes. For now, its is automatic. When you create a new account TouchID is automatically set on. This, I think wil be preferred by most users. In fact I think we will have more folks wondering why it is not the default that not.

**Comment by daviddahl** [comment]
Naturally, we need to think through how to really handle this after an appropriate amount of user feedback comes in:) I could be totally wrong.
