### ISSUE TITLE
[crypton] convert _trust_state container to an item

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#19]
We should also rename it _crypton_contacts or something to make it more understandable. This is a list of trusted contacts.

**Comment by ecto** [comment]
+1 to making `_trust_state` an Item

**Comment by daviddahl** [comment]
Heh: https://github.com/SpiderOak/crypton/commit/e7edc5655c34ed0ba48c055d26760ea2d9b84903

**Comment by daviddahl** [comment]
We are seeing weird things on mobile with any container usage - mainly "signatures that do not verify", etc and this seems to kill the rest of the app intialization

**Comment by daviddahl** [comment]
BTW: this app even runs fast on iPhone 5 iOS 8

**Comment by daviddahl** [comment]
This was fixed in https://github.com/SpiderOak/crypton/tree/excise-trust-state-container
