### ISSUE TITLE
Camera upside down on stock Android M

### ISSUE THREAD

**Issue by shibco** [Crypton/statusapp#209]
Just installed Kloak on a brand new Nexus 5X, and when I try to barcode scan other users, the camera is upside down!

Steps to reproduce:
1. Buy a 5X
2. Install Kloak
3. Navigate to Contacts > Add Contact
4. Marvel at upside down camera 😩

**Comment by devgeeks** [comment]
I wonder if this is an issue with Marshmallow?

**Comment by shibco** [comment]
Is anyone else able to reproduce this?

**Comment by devgeeks** [comment]
I am booting up my Nexus 5 with M right now...

**Comment by daviddahl** [comment]
Nope. But I dont have a nexus

**Comment by devgeeks** [comment]
OK. For me it wasn't upside down... it did default to landscape, however.

This is not unexpected though.
