### ISSUE TITLE
Install Kloak

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#216]
# Steps to reproduce issue

Verify that Kloak can be installed over previous versions.
Verify that Kloak can be installed fresh.
# Actual result

Could not install over previous version of Kloak Android OR iOS
# Other information

Reported by: Renee Jackson 

Test case number: TC01 

Test run: [https://spideroak.testlodge.com/projects/14421/runs/191185?tab=2&run_section_id=165466&executed_case_id=9265225#executed_case_9265225](https://spideroak.testlodge.com/projects/14421/runs/191185?tab=2&run_section_id=165466&executed_case_id=9265225#executed_case_9265225)

**Comment by daviddahl** [comment]
This is a non-issue as no one will ever try to install an ad-hoc Kloak over an appstore install. You should just save your passphrase, delete kloak from the appstore and try to install from the adhoc url.
