### ISSUE TITLE
Deleting a contact

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#222]
# Description

Removing a contact from your list.
# Steps to reproduce issue

click on the contacts icon in the upper right hand corner
click on an individual contact to view their details
select Delete Contact and confirm to unshare feed.
# Expected result

Given User 1 and User 2 have both scanned each other's QR codes

2 deletes 1 as a contact

1 no longer sees 2's posts but 2 continues to see 1's posts.

Once you accept a contact card, yout status will always be sent to them as they are considered "trusted" and the status Item Object is shared to them.
With current behavior there is no way to "unfollow" someone, only to stop sending them your updates.
# Actual result

in Android only contact still shows as a contact after being deleted. When I try to readd that contact it says "peer already trusted" further confirming that it was not deleted to begin with.
# Other information

Reported by: Renee Jackson 

Test case number: TC15 

Test run: [https://spideroak.testlodge.com/projects/14421/runs/192188?tab=2&run_section_id=167345&executed_case_id=9306262#executed_case_9306262](https://spideroak.testlodge.com/projects/14421/runs/192188?tab=2&run_section_id=167345&executed_case_id=9306262#executed_case_9306262)

**Comment by reneelynn** [comment]
In the version from last night (02/08/16 10:56pm) this is not reproducing

**Comment by daviddahl** [comment]
yeah, I also was unable to reproduce this.
