### ISSUE TITLE
Feature recommendation - Busy/Free

### ISSUE THREAD

**Issue by cHRIScDammit** [Crypton/statusapp#29]
I've always wanted to add physical stoplights to people's desks. Interruption can be a productivity killer but sometimes it is necessary. The thought behind the stoplight would be to signal to others your availability for an unscheduled conversation. Red=No, Green=Yes, Yellow=Hi Importance Only.

Theoretically, everyone should allow some time for each and there is likely some ideal split (ex. 20% Red/60% Yellow/20% Green). Down the road, some metrics for both users and managers might be interesting.

**Comment by daviddahl** [comment]
I can imagine adding a "mood" border (maybe 4 pixels on the right) that defaults white, but can be set to green, yellow, red - maybe black for "WTF blocked and pissed need air"?

**Comment by helveticade** [comment]
Out of scope for current version. We will revisit this once we got a core set of features done. Consider it closed but not forgotten!
