### ISSUE TITLE
Update timestamps on status items when resume() or refresh() is called

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#41]
![img_0676](https://cloud.githubusercontent.com/assets/3867179/7634508/f58d8280-fa20-11e4-9435-2f7094c41a92.jpg)

**Comment by daviddahl** [comment]
Indeed, there is no updateTimestamps() function yet. They are frozen in time inside the UI. I need to add a data attribute to each status item and update the timestamps each time you refresh or resume the application.

**Comment by helveticade** [comment]
These now have absolute timezones.
