### ISSUE TITLE
Multiple "hello world" first statuses

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#42]
![img_0672](https://cloud.githubusercontent.com/assets/3867179/7634518/04518b40-fa21-11e4-9b6f-175fa90cecac.jpg)

**Comment by daviddahl** [comment]
There is also a bug where you "lose" the most recent posts if you re-login right away until the next time you login. It turns out timelines are way more complicated than I thought.

**Comment by daviddahl** [comment]
I think this is fixed
