### ISSUE TITLE
Status does not escape markup

### ISSUE THREAD

**Issue by Bennyoak** [Crypton/statusapp#49]
Status updates do not escape html markup.
In a test p, ul and li tags process and render.
Additionally - non html markup is processed e.g. `</rant>`

**Comment by daviddahl** [comment]
Oh yeah, this is bad. Will try to fix this asap

**Comment by daviddahl** [comment]
Fixed in commit 6e1bd9c94823232adf0b268fbfdc3b6b8daa52cd
