### ISSUE TITLE
Investigate mysterious logouts

### ISSUE THREAD

**Issue by narayandesai** [Crypton/statusapp#50]
The current build of the android app logs me out unpredictably (twice in the last hour)

**Comment by daviddahl** [comment]
Interesting, btw, what version of android are you running?

**Comment by narayandesai** [comment]
Android 5.0.2 (it is a samsung galaxy s6, with a stock load).

**Comment by daviddahl** [comment]
interesting, have not tested on Android 5 yet

**Comment by daviddahl** [comment]
I have now tested this on android 5 latest via the emulator and have not experienced this problem. A new android build is in this repo in the iOS-testing branch inside mobileapp/dist

**Comment by helveticade** [comment]
![Sigh.](https://media.giphy.com/media/jWeHpEGSscp2/giphy.gif)
