### ISSUE TITLE
offline.js support

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#55]
Steal the code from Encryptr:)

**Comment by devgeeks** [comment]
:+1:

**Comment by daviddahl** [comment]
can you point me to your implementation?

**Comment by devgeeks** [comment]
https://github.com/devgeeks/Encryptr/blob/master/www/index.html#L7
https://github.com/devgeeks/Encryptr/blob/master/www/index.html#L62

...and, finally:

https://github.com/devgeeks/Encryptr/blob/master/src/app.js#L36-L69


I have also tweaked the css slightly:

https://github.com/devgeeks/Encryptr/blob/master/www/css/index.css#L568-L575

**Comment by daviddahl** [comment]
Fixed in commit 4715361084dcddbc821a9745c9360f83bdb96500
