### ISSUE TITLE
Make sure deleting a contact removes shared status as well

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#59]
I have noticed some problems getting access back to a peer's status updates after a deletion and re-adding of a contact

**Comment by daviddahl** [comment]
Also, when re-adding a peer, we must share the status item with them and share the avatar item with them.

**Comment by Bennyoak** [comment]
@daviddahl - Looks like you've already addressed the remove share portion in: https://github.com/Crypton/statusapp/blob/master/mobileapp/www/js/index.js#L341 ?

**Comment by daviddahl** [comment]
Yeah, this code just needs a lot of testing to make sure nothing falls through the gaps

**Comment by daviddahl** [comment]
fixed in 40cf4313f55492615e5e729000a68b3b2ad3f3b0
