### ISSUE TITLE
Test card capture via "load..."

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#62]
Maybe not working after some recent hcking

**Comment by qdonnellan** [comment]
Confirmed on android 5.1.1 (Nexus 5), click on "Load file", selected image just fine, then goes back to Verify Contact Card screen with no feedback on success/failure. Contact is not added.

**Comment by daviddahl** [comment]
Something fishy on Android 5 when an account is created methinks

**Comment by daviddahl** [comment]
WFM now, I believe this was related to the Android 5 networking problem
