### ISSUE TITLE
Adding one's self as contact kills the app

### ISSUE THREAD

**Issue by Bennyoak** [Crypton/statusapp#63]
So because I like breaking things, I decided to add my own contact card to my list of trusted contacts.
The result is as follows:
- Upon adding received duplicates of existing self posts
  - Received quadruples of new self posts
- Closing the app out of background and logging back in:
  - App stalls on "Loading contacts and preferences" view
  - Can navigate to other views, but can't do anything
- Removing self as contact fails and creates a loop where confirming delete leads back to Delete Contact view

Device: iPhone 5s / iOS 8.4(12H143)

**Comment by daviddahl** [comment]
Fixed in commit 9e54b6d1a5d6ee33e8f3a140f955340e5d180813
