### ISSUE TITLE
Better UX for Menu

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#71]
Kloak's menu contains both actions and modes, (eg Update Status as an action vs Contacts as a mode). A better UX would be to separate actions from Kloak's navigation and place them in their respective modes.
I suggest the following navigation structure:

- Timeline
- Contacts
- Options

**Comment by daviddahl** [comment]
Like a set of tabs along the top? 
| Timeline | Contacts | Options |

**Comment by helveticade** [comment]
The existing hamburger menu is fine for this. 

If we were to follow convention, a 3-tab title bar would be appropriate for Material Dedign. On iOS, the most appropriate execution would be a bottom tab bar. 

I am not a fan of pushing navigation to the top of an interface, as it's extremely difficult to reach. But I'm also not in favour of making radical changes for this current beta.

**Comment by daviddahl** [comment]
If I remove "Update Status" and "Feed/Timeline" we will be left with Contacts, My Contact Card, Options, About and Logout, which seems too few to matter, no?

**Comment by daviddahl** [comment]
also, I need a "logout" icon

**Comment by daviddahl** [comment]
![img_0821](https://cloud.githubusercontent.com/assets/23880/9263109/eeb52236-41df-11e5-8d67-f091caa27a00.png)

**Comment by daviddahl** [comment]
The above menu is already so much simpler, just missing the logout button, which is maybe unneeded anyway?

**Comment by helveticade** [comment]
Yeah, it's almost there.

Drop My Contact Card and About, and add Timeline back. We can make My contact card a primary action in Contacts, and About/Log Out actions in Options.

**Comment by daviddahl** [comment]
oh, nice.

**Comment by daviddahl** [comment]
one slight difference is that the timeline option did not call "sync" in the menu, merely gets you back to the cached timeline items. We might want a different icon for this, no?

**Comment by helveticade** [comment]
Can we initiate a sync when a user navigates to the Timeline menu option?

**Comment by daviddahl** [comment]
We can do that, I think my view is too nuanced, etc

**Comment by helveticade** [comment]
:+1: :sparkles:

**Comment by daviddahl** [comment]
![ios simulator screen shot aug 21 2015 12 36 04 pm](https://cloud.githubusercontent.com/assets/23880/9414871/3bf02376-4801-11e5-93f2-e9664573954f.png)
Calling this done for now. So simple.
