### ISSUE TITLE
Filter actions into relevant navigation items

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#72]
On the basis of #71, we can filter certain actions into their relevant navigation structure.

- Feed
Primary action: New post
Secondary action: Refresh

- Contacts
Primary action: Add contact
Secondary actions: Refresh, My Contact Card

- Options
Primary action: None.
Secondary action: About/help (combined)

**Comment by daviddahl** [comment]
fixed via #71 which is so much simpler
