### ISSUE TITLE
Revise iconography

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#73]
Create icon set for Kloak that's more legible than the current set.

**Comment by helveticade** [comment]
<img width="1024" alt="kloak prototype icon" src="https://cloud.githubusercontent.com/assets/737950/9079494/0661de40-3b8e-11e5-90dc-407b57b37187.png">
Icon concept for Beta 2. Guaranteed this will change over time, but I'm ok with this given the deadline and my current workload.

**Comment by daviddahl** [comment]
While this is interesting, It has a definite "Chat" connotation to it, whereas, Kloak is much more about a casual status tool a'la Facebook's Wall or Twitter's feed. The idea around the name "Kloak" is the Silicon Valley hoodie that is the uniform of the Zuckerbergs of this world. Kloak's mission is to demonstrate that we can have the rich experience without the deal with the devil: Datamining. I want the imagery to be a tounge-in-cheek poke at the hoodie-wearing-privacy-destroying culture thereof.

**Comment by helveticade** [comment]
How about something like this?
<img width="1024" alt="kloak beta icon option 2" src="https://cloud.githubusercontent.com/assets/737950/9148810/3ea9bc86-3dce-11e5-8cc8-7271c67a815a.png">
(I want to redraw this, right now it uses (this icon)[https://thenounproject.com/search/?q=hoodie&i=24288] by Snugsack)

**Comment by daviddahl** [comment]
That is really good

**Comment by daviddahl** [comment]
this is fixed via commit f46a5f1f5ecf80f5456c83de113efa3367c40b79

**Comment by daviddahl** [comment]
naturally, if @helveticade wants more changes we can re-open or create a new issue
