### ISSUE TITLE
Improve legibility of status updates

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#74]
When posting to Kloak, the created message's hierarchy and layout is a little unbalanced. @daviddahl, I'll post a revised layout here.

**Comment by daviddahl** [comment]
sweet!

**Comment by helveticade** [comment]
Yo, here's a quick example of better status messages. ![message example](https://cloud.githubusercontent.com/assets/737950/9076623/47a8e2d4-3b68-11e5-8875-5fa22d966f32.png)

For font sizing, etc, refer to [Material Design typography guidelines](https://www.google.com/design/spec/style/typography.html#typography-styles) for now.

**Comment by daviddahl** [comment]
Ironically, this is an image: https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7dENFMU0yMTJ0YTQ/style_typography_styles_scale.png 

LOL

**Comment by helveticade** [comment]
:turtle:

**Comment by daviddahl** [comment]
fixed in f632b4165355a157e02dc0ce5a3f5553a5d4f4d5
