### ISSUE TITLE
Hide all menu button svgs before login

### ISSUE THREAD

**Issue by merickson** [Crypton/statusapp#88]
When starting the app, it tries to take me to the login screen before it pops up the view for logging me in. The views unload oddly, so it results in an ugly login screen.

See https://vimeo.com/137405580 for a video of the issue.

**Comment by merickson** [comment]
Vimeo is made of soot and poo. Better link to the video here: https://spideroak.com/share/OBSWC53FMVWWC5DU/bugvideos/Users/matt/SpiderOak%20Hive/bugvideo/funnyui.mov

**Comment by daviddahl** [comment]
Fascinating. I think we need to hide more stuff on first launch, only un-hiding after login is complete. Thanks for the report. My device does not do this at all.

**Comment by Bennyoak** [comment]
Yeah I've been looking in that direction. We can solve a lot of this by wrapping more things inside init() as functions themselves.

**Comment by daviddahl** [comment]
We will fix this in the general "On-boarding" re-design

**Comment by daviddahl** [comment]
Fixed in b-4 branch
