### ISSUE TITLE
Http://zk.gs error

### ISSUE THREAD

**Issue by peterrrrr** [Crypton/statusapp#89]
Using my phones browser i get a pop up notification. I will try to attach the screenshot.

**Comment by daviddahl** [comment]
you just drag it into the area you type into in this issue:)

**Comment by peterrrrr** [comment]
God Dammit!

**Comment by peterrrrr** [comment]
![screenshot_2015-08-27-13-48-53](https://cloud.githubusercontent.com/assets/8041865/9531087/888b14d0-4cc9-11e5-8083-8e520e54b313.png)

**Comment by daviddahl** [comment]
You are visiting the wrong page. Also, that page does indeed use WebRTC:)
