### ISSUE TITLE
Proper cert for nw builds

### ISSUE THREAD

**Issue by daviddahl** [Crypton/statusapp#9]
[15553:0320/180221:ERROR:cert_verify_proc_nss.cc(886)] CERT_PKIXVerifyCert for [redacted].[com] failed err=-8181

**Comment by devgeeks** [comment]
In nw.js, you can set Chromium flags... so you can disable web security while debugging before getting a real cert.

try this in `www/package.json`:

`"chromium-args": "--ignore-certificate-errors"`

**Comment by helveticade** [comment]
Desktop, out of scope for the time being.
