### ISSUE TITLE
Password generator can make too long passwords

### ISSUE THREAD

**Issue by bytex64** [Crypton/statusapp#93]
The password generator on the signup dialog will helpfully create passwords that are too long for the login password input box, and let you create an account with them.

**Comment by daviddahl** [comment]
yep. this entire on boarding process is going to be re-written so this is not the case - also it should prompt the user to save the passphrase (to a passwd manager) after the account is created, etc

**Comment by daviddahl** [comment]
A quick fix is actually using a textarea with 2 rows as the input

**Comment by daviddahl** [comment]
Fixed in "onboarding" work in b-4 branch
