### ISSUE TITLE
Better presentation of status update metadata

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#94]
Currently, we're serving a timestamp + obsfucated GPS lat/lon + reverse geocoded city name. This is way too much for a footer, and should be cut down to (by default) a relative time stamp and the city name, eg:

"23 minutes ago _near Chicago, IL_"

Post 1.0 should contain a setting that allows a user to set relative or absolute timestamps.
@daviddahl it's your call, but post footers are a huge drag rn

**Comment by helveticade** [comment]
Maybe location could be like this, too? We could easily split the location item in the status object into it's own object with two items, "coordinates" and "geocoded."

**Comment by daviddahl** [comment]
With a relative time stamp we will need to write a bunch of code to run on each resume() event that updates them all. Not sure if we need to do this now.

**Comment by helveticade** [comment]
We could probably designate this to a jQuery date library, tbqh.

**Comment by devgeeks** [comment]
Relative is done at display time. Just use moment.js

`moment(timestamp+'', 'X').fromNow()`

**Comment by devgeeks** [comment]
moment can even be localised.

**Comment by helveticade** [comment]
+1

**Comment by daviddahl** [comment]
We already have moment.js loaded

**Comment by daviddahl** [comment]
this is half fixed

**Comment by daviddahl** [comment]
fix in b-4 branch
