### ISSUE TITLE
Make the header on my ui branch context aware

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#95]
My header is fixed globally and doesn't respect the current view, lol. That needs to change and I don't have time to do that.
![lol](https://media.giphy.com/media/uGdkIHpNX0Twk/giphy.gif)

**Comment by daviddahl** [comment]
Sounds like we need a function that writes the correct header into each view as app.switchView() is called.

**Comment by daviddahl** [comment]
i think we have fixed this in the general design refresh we are in the midst of
