### ISSUE TITLE
Prevent photo overwrite

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#97]
When a user taps "take a photo" when they're viewing their own contact card – and then aborts the operation – Kloak deletes their previously saved photo. This is a huge downer.

**Comment by daviddahl** [comment]
This should display an action sheet that has "Pick photo", "Take Photo", "Cancel"

**Comment by devgeeks** [comment]
If you don't want to rewrite the wheel, there are action sheet plugins

https://github.com/EddyVerbruggen/cordova-plugin-actionsheet

etc

**Comment by daviddahl** [comment]
Already added it to my local checkout:) Thanks!

**Comment by daviddahl** [comment]
Fixed in b-4 as we are now using an action sheet
