### ISSUE TITLE
Crop a square user avatar photo on upload

### ISSUE THREAD

**Issue by helveticade** [Crypton/statusapp#98]
The current design uses portrait dimensions, which feels really wonky. Kloak should – if this is possible in Cordova – present a square camera mode similar to iOS's camera options, and crop a square version. Could also just crop a photo top/bottom automatically without user input.

**Comment by daviddahl** [comment]
we can do a crop in a non-automatic way via canvas, but I am unsure about taking a square photo. Maybe @devgeeks knows?

**Comment by devgeeks** [comment]
What you might wanna try is `allowEdit: true` in the camera options.

**Comment by daviddahl** [comment]
ohhhh "allowEdit", however, this will be an opt-in thing, yeah?

**Comment by devgeeks** [comment]
Might still need to limit this to just the avatar, not ALL pictures...

**Comment by daviddahl** [comment]
Fixed in b-4
