### ISSUE TITLE
New account creation fails

### ISSUE THREAD

**Issue by reneelynn** [Crypton/statusapp#99]
1) my old credentials for Kloak are still saved
2) Create new account
3) Account creation seems to work but ultimately fails with “incorrect password” errors
4) Subsequent attempts to log in to that account give the same error
5) Attempts to create subsequent accounts with that username fail with “username taken"

**Comment by daviddahl** [comment]
Thanks! I knew about this but have yet been able to file it. A quick note, when a new account is being created and there is an existing account, we need to set a flag so we don't attempt to use stored credentials. This should be a 5 line fix if I remember correctly.

**Comment by Bennyoak** [comment]
I'm working on a couple of side-long tickets that may help this.

**Comment by daviddahl** [comment]
Fixed in new onboarding code
